version: '3.8'
services:
  mongodb:
    # using the bitnami image to avoid transaction issues when testing
    image: bitnami/mongodb:5.0
    ports:
      - "27017:27017"
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: password
      MONGODB_REPLICA_SET_KEY: 123456

  # Mongo Express Service
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb